name: 'lakehouse'
version: '1.0.0'
config-version: 2

profile: 'lakehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  +reflection_refresh: True
  +reflection_refresh_wait_timeout: 300
  +use_metadata_cache: False
  +create_or_replace: True
  lakehouse:
    bronze:
      +materialized: view
      +on_table_exists: drop
      +twin_strategy: allow
      +object_storage_path: bronze

    silver:
      +materialized: table
      +on_table_exists: drop
      +twin_strategy: allow
      +object_storage_path: silver

    gold:
      +materialized: table
      +on_table_exists: drop
      +object_storage_path: gold
      +twin_strategy: allow
