select
    md5(source_key) as id_dim_country,
    source_key,
    country,
    coalesce(independent, '-') as independent,
    coalesce(iso_3166_1_alpha2, '-') as iso_3166_1_alpha2,
    coalesce(iso_3166_1_alpha3, '-') as iso_3166_1_alpha3,
    coalesce(name_preferred, '-') as name_preferred,
    coalesce(name_english, '-') as name_english,
    coalesce(name_french, '-') as name_french,
    coalesce(name_spanish, '-') as name_spanish,
    coalesce(name_russian, '-') as name_russian,
    coalesce(name_chinese, '-') as name_chinese,
    coalesce(name_arabic, '-') as name_arabic,
    coalesce(region_code, '-') as region_code,
    coalesce(region_name, '-') as region_name,
    coalesce(sub_region_code, '-') as sub_region_code,
    coalesce(sub_region_name, '-') as sub_region_name,
    coalesce(intermediate_region_code, '-') as intermediate_region_code,
    coalesce(intermediate_region_name, '-') as intermediate_region_name,
    coalesce(world_bank_income_level, '-') as world_bank_income_level,
    coalesce(currency, '-') as currency,
    coalesce(period_start, '-') as period_start,
    coalesce(flag, '-') as flag
from {{ ref('transf_dim_country') }}