models:
  - name: fact_invoice
    description: The 'fact_invoice' model is a fact table that contains transactional data related to invoices. It includes columns for the source key, quantity, price, VAT, total amount excluding VAT, total amount including VAT, and hashed identifiers for product, customer, and country. The source key is a combination of the invoice and stock code. The VAT is a fixed value of 18. The total amounts are calculated based on the quantity and price. The identifiers for product, customer, and country are hashed for security reasons.
    columns:
      - name: source_key
        description: A unique identifier for each invoice, created by concatenating the invoice number and stock code.
        data_type: character varying
        tests:
          - unique
        quote: true
      - name: quantity
        description: The quantity of the product sold in the invoice.
        data_type: decimal
        quote: true
      - name: price
        description: The price of the product sold per unit.
        data_type: decimal
        quote: true
      - name: vat
        description: This column represents the Value Added Tax (VAT) rate applied to the product. In this model, it is a constant value of 18, indicating a VAT rate of 18%.
        data_type: integer
        quote: true
      - name: total_amount_exc_vat
        description: This column represents the total amount of the invoice excluding VAT. It is calculated as the product of quantity and price divided by (1 + VAT rate), where the VAT rate is 0.18.
        data_type: decimal
        quote: true
      - name: total_amount_inc_vat
        description: This column represents the total amount of the invoice including VAT. It is calculated as the product of quantity and price.
        data_type: decimal
        quote: true
      - name: id_dim_product
        description: This is a unique identifier for each product. It is generated by applying the MD5 hash function to the stock_code of each product.
        data_type: character varying
        tests:
          - relationships:
              field: id_dim_product
              to: ref('dim_product')
        quote: true
      - name: id_dim_customer
        description: This is a unique identifier for each customer. It is generated by applying the MD5 hash function to the customer_id of each customer.
        data_type: character varying
        tests:
          - relationships:
              field: id_dim_customer
              to: ref('dim_customer')
        quote: true
      - name: id_dim_country
        description: This is a unique identifier for each country. It is generated by applying the MD5 hash function to the country name.
        data_type: character varying
        tests:
          - relationships:
              field: id_dim_country
              to: ref('dim_country')
        quote: true
  - name: dim_product
    description: "The 'dim_product' model is a transformation of the 'transf_dim_product' table from the 'silver' schema in the 'lakehouse' database. It contains four columns: 'id_dim_product', 'source_key', 'code', and 'description'. The 'id_dim_product' column is a hashed version of the 'source_key' column, generated using the MD5 algorithm. The 'source_key' column is a unique identifier for each product. The 'code' column represents the product code, and the 'description' column provides a description of the product."
    columns:
      - name: id_dim_product
        description: This is a unique identifier for each product in the dimension table. It is generated by applying the MD5 hash function to the source_key.
        data_type: character varying
        tests:
          - unique
        quote: true
      - name: source_key
        description: This is the original key from the source system that uniquely identifies each product.
        data_type: character varying
        tests:
          - unique
        quote: true
      - name: code
        description: This is the product code associated with each product. It is a unique identifier provided by the source system.
        data_type: character varying
        quote: true
      - name: description
        description: This column contains the detailed description of the product.
        data_type: character varying
        quote: true
  - name: dim_customer
    description: "The 'dim_customer' model is a dimension table that contains information about customers. It is derived from the 'transf_dim_customer' table in the 'silver' schema of the 'lakehouse' database. The model includes the following columns: 'id_dim_customer', 'source_key', 'code', and 'name'. The 'id_dim_customer' column is a hashed version of the 'source_key' column, generated using the MD5 function."
    columns:
      - name: id_dim_customer
        description: This is a unique identifier for each customer. It is generated by applying the MD5 hash function to the source_key.
        data_type: character varying
        tests:
          - unique
        quote: true
      - name: source_key
        description: This is the original key from the source data. It is used to generate the id_dim_customer field.
        data_type: character varying
        quote: true
      - name: code
        description: This is a code associated with each customer. The specific meaning and use of this code may vary depending on the context.
        data_type: character varying
        quote: true
      - name: name
        description: This column contains the name of the customer.
        data_type: character varying
        quote: true
  - name: dim_country
    description: The 'dim_country' model is a dimension table that contains information about different countries. It includes columns for the country's name in various languages, its ISO codes, region and sub-region codes and names, World Bank income level, currency, and a flag. The 'source_key' is a unique identifier for each country, and 'id_dim_country' is a hashed version of this key. The 'independent' column indicates whether the country is independent or not. The 'period_start' column indicates the start of the period for which the data is valid. If any information is missing, it is replaced with a '-' character.
    columns:
      - name: id_dim_country
        description: This is a unique identifier for each country. It is generated by applying the MD5 hash function to the source_key.
        data_type: character varying
        tests:
          - unique
        quote: true
      - name: source_key
        description: This is the original key from the source data. It is used to generate the id_dim_country.
        data_type: character varying
        quote: true
      - name: country
        description: This is the name of the country. It is a character varying type, meaning it can hold any string value.
        data_type: character varying
        quote: true
      - name: independent
        description: This column indicates whether the country is independent or not. The value is either 'Yes' for independent countries or 'No' for dependent territories. If the information is not available, the value is set to '-'.
        data_type: character varying
        quote: true
      - name: iso_3166_1_alpha2
        description: This column contains the two-letter country codes defined in ISO 3166-1, part of the ISO 3166 standard published by the International Organization for Standardization (ISO), to represent countries, dependent territories, and special areas of geographical interest. If the information is not available, the value is set to '-'.
        data_type: character varying
        quote: true
      - name: iso_3166_1_alpha3
        description: This column contains the three-letter country codes defined in ISO 3166-1, part of the ISO 3166 standard published by the International Organization for Standardization (ISO), to represent countries, dependent territories, and special areas of geographical interest. If the information is not available, the value is set to '-'.
        data_type: character varying
        quote: true
      - name: name_preferred
        description: The preferred name of the country in its official language.
        data_type: character varying
        quote: true
      - name: name_english
        description: The name of the country in English.
        data_type: character varying
        quote: true
      - name: name_french
        description: The name of the country in French.
        data_type: character varying
        quote: true
      - name: name_spanish
        description: The official name of the country in Spanish language.
        data_type: character varying
        quote: true
      - name: name_russian
        description: The official name of the country in Russian language.
        data_type: character varying
        quote: true
      - name: name_chinese
        description: The official name of the country in Chinese language.
        data_type: character varying
        quote: true
      - name: name_arabic
        description: The Arabic name of the country. If no Arabic name is available, the value will be '-'.
        data_type: character varying
        quote: true
      - name: region_code
        description: The code representing the region of the country. If no region code is available, the value will be '-'.
        data_type: character varying
        quote: true
      - name: region_name
        description: The name of the region where the country is located. If no region name is available, the value will be '-'.
        data_type: character varying
        quote: true
      - name: sub_region_code
        description: The sub_region_code is a character varying field that represents the code of the sub-region where the country is located. It is derived from the source data and if not available, it is replaced with a '-' character.
        data_type: character varying
        quote: true
      - name: sub_region_name
        description: The sub_region_name is a character varying field that represents the name of the sub-region where the country is located. It is derived from the source data and if not available, it is replaced with a '-' character.
        data_type: character varying
        quote: true
      - name: intermediate_region_code
        description: The intermediate_region_code is a character varying field that represents the code of the intermediate region where the country is located. It is derived from the source data and if not available, it is replaced with a '-' character.
        data_type: character varying
        quote: true
      - name: intermediate_region_name
        description: The name of the intermediate region where the country is located. If the country does not belong to an intermediate region, the value will be '-'.
        data_type: character varying
        quote: true
      - name: world_bank_income_level
        description: The income level of the country as classified by the World Bank. If the income level is not available, the value will be '-'.
        data_type: character varying
        quote: true
      - name: currency
        description: The official currency used in the country. If the currency is not available, the value will be '-'.
        data_type: character varying
        quote: true
      - name: period_start
        description: The start date of the period for which the data is relevant. This is a string representation of a date, but the exact format may vary depending on the source data.
        data_type: character varying
        quote: true
      - name: flag
        description: A string representation of the country's flag. The exact format of this data may vary depending on the source data.
        data_type: character varying
        quote: true
  - name: dim_calendar
    columns:
      - name: date_day
        description: This column represents the date in the format YYYY-MM-DD. It is the primary key for the dim_calendar model.
        data_type: date
        quote: true
      - name: id_dim_calendar
        description: This column is a unique identifier for each date in the dim_calendar model. It is generated by hashing the date (in the format YYYYMMDD) using the MD5 algorithm.
        data_type: character varying
        tests:
          - unique
        quote: true
      - name: date_yyyymmdd
        description: This column represents the date in the format YYYYMMDD. It is derived from the date_day column.
        data_type: character varying
        quote: true
      - name: day_of_year
        description: This column represents the day of the year for the given date. It is calculated using the DAY_OF_YEAR function on the date_day column. The value is a bigint.
        data_type: bigint
        quote: true
      - name: dayofweek
        description: This column represents the day of the week for the given date. It is calculated using the DAY_OF_WEEK function on the date_day column. The value is a bigint, where 1 represents Sunday, 2 represents Monday, and so on till 7 which represents Saturday.
        data_type: bigint
        quote: true
      - name: dayofweek_name
        description: This column represents the name of the day of the week for the given date. It is calculated using a CASE statement on the dayofweek column. The value is a string, where '1' represents 'SUNDAY', '2' represents 'MONDAY', and so on till '7' which represents 'SATURDAY'. Any other value is represented as 'N/I'.
        data_type: character varying
        quote: true
      - name: day_of_month
        description: This column represents the day of the month for each date in the 'date_day' column. It is extracted from the 'date_day' column using the EXTRACT function in SQL.
        data_type: bigint
        quote: true
      - name: week_start_date
        description: This column represents the start date of the week for each date in the 'date_day' column. It is calculated by subtracting the day of the week from the 'date_day' column.
        data_type: date
        quote: true
      - name: week_end_date
        description: This column represents the end date of the week for each date in the 'date_day' column. It is calculated by adding the difference of 6 and the day of the week to the 'date_day' column.
        data_type: date
        quote: true
      - name: week_of_year
        description: This column represents the week number of the year for the given date. It is extracted from the 'date_day' column using the WEEK function in SQL.
        data_type: bigint
        quote: true
      - name: month_of_year
        description: This column represents the month number of the year for the given date. It is extracted from the 'date_day' column using the MONTH function in SQL.
        data_type: bigint
        quote: true
      - name: month_start_date
        description: This column represents the start date of the month for the given date. It is calculated by truncating the 'date_day' column to the month level using the DATE_TRUNC function in SQL.
        data_type: date
        quote: true
      - name: month_end_date
        description: This column represents the end date of the month for the given date_day. It is calculated by truncating the date_day to the start of the month and then adding 30 days to it.
        data_type: date
        quote: true
      - name: quarter_of_year
        description: This column represents the quarter of the year for the given date_day. It is extracted directly from the date_day using the EXTRACT function.
        data_type: bigint
        quote: true
      - name: quarter_start_date
        description: This column represents the start date of the quarter for the given date_day. It is calculated by truncating the date_day to the start of the quarter.
        data_type: date
        quote: true
      - name: quarter_end_date
        description: This column represents the end date of the quarter for the given date. It is calculated by adding 89 days to the start date of the quarter.
        data_type: date
        quote: true
      - name: year_number
        description: This column represents the year of the given date. It is extracted directly from the date_day column.
        data_type: bigint
        quote: true
      - name: year_start_date
        description: This column represents the start date of the year for the given date. It is calculated by truncating the date_day to the start of the year.
        data_type: date
        quote: true
      - name: year_end_date
        description: This column represents the end date of the year for the given date. It is calculated by adding 364 days to the start date of the year.
        data_type: date
        quote: true
      - name: rec_inserted_at
        description: This column represents the timestamp when the record was inserted into the database. It is automatically populated with the current timestamp at the time of insertion.
        data_type: timestamp
        quote: true
      - name: rec_updated_at
        description: This column represents the timestamp when the record was last updated in the database. It is automatically populated with the current timestamp at the time of any update.
        data_type: timestamp
        quote: true
    description: The dim_calendar model is a dimension table that provides detailed information about dates. It includes columns for the date, day of the year, day of the week, day of the month, start and end of the week, week of the year, month of the year, start and end of the month, quarter of the year, start and end of the quarter, year, start and end of the year, and timestamps for when the record was inserted and updated. The model is generated from the 'transf_calendar' table in the 'silver' schema of the 'lakehouse' database.
